config/routes.rb
Rails.application.routes.draw do
  get 'pars/index'
  get 'pars/show'
  get 'pars/new'
  get 'pars/create'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :pars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/par.rb
class Par < ApplicationRecord
    geocoded_by :name  # or use an address column if available
    after_validation :geocode, if: :will_save_change_to_name?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/pars_controller.rb
class ParsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @pars = Par.all
    @markers = @pars.geocoded.map do |par|
      {
        lat: par.latitude,
        lng: par.longitude
      }
    end
  end

  def show
    @par = Par.find(params[:id])
    @markers = [{
        lat: @par.latitude,
        lng: @par.longitude
      }]
  end

  def new
    @par = Par.new
  end

  def create
    @par = Par.new(par_params)
    if @par.save
      redirect_to @par, notice: "Park and Ride location created successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def par_params
    params.require(:par).permit(:name, :latitude, :longitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cota</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>COTA APP</h1>
<p>Welcome to the COTA APP!</p>

app/views/pars/create.html.erb
<h1>Pars#create</h1>
<p>Find me in app/views/pars/create.html.erb</p>

app/views/pars/index.html.erb
<h1>All Park and Ride Locations</h1>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<ul>
  <% @pars.each do |par| %>
    <li>
      <%= link_to par.name, par_path(par) %>  
      (<%= par.latitude %>, <%= par.longitude %>)
    </li>
  <% end %>
</ul>

<%= link_to "Add New Location", new_par_path %>

app/views/pars/new.html.erb
<h1>New Park and Ride Location</h1>

<%= form_with model: @par, local: true do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  
  <div>
    <%= form.label :latitude %><br>
    <%= form.number_field :latitude, step: 0.000001 %>
  </div>

  <div>
    <%= form.label :longitude %><br>
    <%= form.number_field :longitude, step: 0.000001 %>
  </div>

  <div>
    <%= form.submit "Create" %>
  </div>
<% end %>

<%= link_to "Back", pars_path %>

app/views/pars/show.html.erb
<h1><%= @par.name %></h1>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<%= link_to "Back", pars_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/3/32/Icon-mode-bus-default.svg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Park and Ride Locations", pars_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>